1주차 미션 제출
Soohyeon02/frontend-mission pull request #1
Opened 2022-01-09 10:43 UTC by Soohyeon02

# 1주차 미션 제출 (황수현)

## 접근 방법

* [x] 미션 코드를 구현하기 위해서 어떤 생각들을 했는지 정리해보세요.
- v-model 을 사용하여 아래에 실시간으로 출력되는 기능을 구현하였습니다.
- 문자열 회전 기능을 구현하기 위해 배열 함수 shift 와 push 의 사용을 고려해보았습니다.
- Clean Code Guide 에 따라 변수명이나 함수명을 자세하고 일관성 있게 작성하였습니다.
- 알림창 구현 부분에서의 warning 을 무시처리 하였습니다.

## 특이사항

* [x] 구현하면서 궁금했던 점이나, 아쉬웠던 부분이 있으면 적어주세요.
- TDD 방법론에 대한 이해가 부족하여 적용하지 못하여 아쉬웠습니다. 추가 자료로 추천해주실만한 자료가 있는지 궁금합니다.
- 알림창 구현 부분에서의 코드가 알맞게 작성되었는지 궁금합니다.
- 컴포넌트에 대한 이해가 부족하여 아쉬웠습니다.
- 추가로 부족한 부분이나 고쳤으면 하는 부분을 피드백 해주시면 빠르게 반영해보겠습니다!

## 제출 후 확인

* [x] 본인의 구현 결과를 `dev` 브랜치에 구현하고, `dev` 브랜치에서 `submission` 브랜치로 PR을 보내주세요.
* [x] Pull Request 생성 후 Reivewer에 @externship-master 와 @lkaybob 을 추가해주세요.

2022-01-10 07:41 UTC, allegoryj commented
안녕하세요 수현님! 그룹 2 정진재입니다.
먼저 미션 요구사항에 있던 기능들을 문제없이 잘 구현해 주신 것 같습니다.
다음번 미션 진행 시에는 TDD 방법론을 적용해서 테스트 코드까지 작성해 보시면 더 좋을 것 같아요!
고생 많으셨습니다. 앞으로도 잘 부탁드립니다:)

2022-01-10 07:43 UTC, allegoryj commented on mission/src/App.vue
> +      this.message = this.message.join('');
slice() 메서드를 사용해 보시면 더 간결하게 코드를 작성해 보실 수 있을 것 같아요!
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/slice

2022-01-10 09:20 UTC, jambottle requested changes
수현님, 안녕하세요? 같은 그룹으로 배정된 김재원이라고 합니다 😃
Code Presentation 영상과 함께 작성하신 코드 잘 봤습니다!

> 저도 처음에는 Jest를 어떻게 써야 하나 난감해서 여러 자료들을 들여다보느라 시간을 많이 썼는데요...
> 그나마 이 강좌가 투입한 시간 대비 가장 Jest를 쉽게 이해할 수 있었던 것 같아 아래에 공유해 드려봅니다 ㅎㅎㅎ
> 
> **🔍참고**(YouTube): https://youtube.com/playlist?list=PLZKTXPmaJk8L1xCg_1cRjL5huINlP2JKt (약 1시간 분량)

미션 수행하시느라 고생 많으셨습니다, 앞으로도 파이팅!!

2022-01-10 09:20 UTC, jambottle commented on mission/src/App.vue
> +    noticeInputAndNumber() {
메서드 이름을 제일 구체적으로 지으신 거 같아요! 👍👍
매번 이름 짓는 게 어렵다고들 하지만, 결국엔 이렇게 정공법으로 짓는 게 답인 것 같습니다 :-D

2022-01-10 09:20 UTC, jambottle commented on mission/src/App.vue
> +      alert(`${this.message} ${this.count}`);
저도 `alert()` 함수를 사용해서 브라우저에 내장된 알림창을 그대로 써볼까 했었는데요...
아래 참고한 공식문서를 보면, 에러 메시지가 뜨는 이유가 나름대로 있더라고요? 🤔 한번 참고해보셔요 ㅎㅎㅎ

**🔍참고**(ESLint Docs): https://eslint.org/docs/rules/no-alert

2022-01-10 09:20 UTC, jambottle commented on mission/src/App.vue
> +      this.message = this.message.join('');
진재님의 코멘트처럼 코드를 작성하게 되면, `arr` 데이터를 하나 덜 써도 된다는 점에서도 한결 깔끔해질 것 같습니다 😁

2022-01-10 09:42 UTC, christianB053 reviewed
안녕하세요 수현님, 2조 김현빈입니다!
코딩 공부를 막 시작한 초보자로 도움되는 리뷰를 하지 못한 점 양해 부탁드립니다.
더더 공부해서 도움이 되는 조원이 되도록 노력하겠습니다!
그럼 남은 미션도 화이팅하세요! :)

2022-01-10 09:42 UTC, christianB053 commented on mission/src/App.vue
> +      this.message = this.message.join('');
문자열 회전 시키기를 구현하지 못했었는데, 수현님 작성한 코드를 보고  shift 메서드를 사용해서 첫 번째 요소를 제거하고 제거한 요소를 push를 이용해 다시 추가해 주는 방법도 있다는 것을 알게 되었습니다!

2022-01-10 09:42 UTC, christianB053 commented on mission/src/App.vue
> +    noticeInputAndNumber() {
수현님 작성한 메서드 이름과 재원님 답변을 통해서 어떻게 이름을 작성해야 하는지 도움이 많이 되었습니다!

2022-01-10 11:45 UTC, ddukddak-kim commented
수현님 안녕하세요 :) 
이번 익스텐션 기간동안 Peer 리뷰를 함께 할 2그룹 김경민 입니다. 
만나서 반가워요~ 😎

이번 주 미션 수행하느라 고생 많으셨습니다-!

2022-01-10 12:09 UTC, Soohyeon02 commented on mission/src/App.vue
> +      this.message = this.message.join('');
안그래도 더 간결한 코드가 없을까 고민에 있었던 참인데 좋은 방법을 공유해주셔서 감사합니다!
앞으로 잘 부탁드립니다 :)

2022-01-10 12:10 UTC, Soohyeon02 commented on mission/src/App.vue
> +      alert(`${this.message} ${this.count}`);
넵 참고해보도록 하겠습니다 감사합니다!

2022-01-10 13:29 UTC, KyubumJang commented on mission/src/App.vue
> +      this.message = this.message.join('');
진재님의 코멘트를 참조하여 slice() 사용하시면 아주 유용하게 사용할 수 있습니다! 데이터 가공할 때도 좋아요!

2022-01-10 13:34 UTC, KyubumJang commented on mission/src/App.vue
> +    noticeInputAndNumber() {
변수명 생각하는게 정말 어렵죠! 클린코드 가이드를 읽어도 아직은 감이 잡히지 않아 Vue 공식문서 스타일가이드 참조해서 변수명 이해하고 쉽게 만들어봐야겠어요!

2022-01-10 13:37 UTC, KyubumJang commented
수현님 안녕하세요! 같은 그룹2로 배정된 장규범입니다.
코드 설명 영상과 commit 남겨주신 것 잘봤습니다. 구현도 잘 됐네요!!
이번 주 미션 수행하시느라 고생 많으셨습니다!👍
앞으로도 잘 부탁드립니다!😊

2022-01-10 15:26 UTC, lkaybob reviewed
요구사항을 충실히 구현해주셨으며, 커밋 메시지를 비롯한 identifier들의 명명을 명시적으로 해주셔서 이해하기 편했습니다.

> TDD 방법론에 대한 이해가 부족하여 적용하지 못하여 아쉬웠습니다. 추가 자료로 추천해주실만한 자료가 있는지 궁금합니다.

추가자료에서 제시해드린 문서를 참고하실 것을 권장드립니다. 간단한 투두리스트 앱에 대한 테스트 코드를 작성해나가기 때문에 테스트 코드 작성을 하시는데 필요한 감을 얻으실 수 있을 겁니다.

https://next.vue-test-utils.vuejs.org/guide/essentials/a-crash-course.html

> 알림창 구현 부분에서의 코드가 알맞게 작성되었는지 궁금합니다.

맞게 해주셨습니다. 원래 의도는 합의된 요구사항에 한해 disable을 하여 린터의 경고를 없애는 것이었지만, 다른 분이 의견 남겨주신 것처럼 알림창을 직접 구현하는 것도 좋은 방법이라고 생각합니다.

2022-01-14 13:20 UTC, jambottle commented on mission/src/App.vue
> +      alert(`${this.message} ${this.count}`);
수현님도 온라인 세션 때 들으셨겠지만, `alert` 함수 관련 에러는...
해당 부분에 `// eslint-disable-next-line no-alert`를 한 줄 추가하는 것만으로도 해결 가능한 것 같습니다!

2022-01-14 14:40 UTC, merged